### ISSUE TITLE
Sorting on Owner and Assigned to columns sorts on guid not the actual display name

### ISSUE THREAD

**Issue by saikovvuri** [NullDesk/ticketdesk#101]
Hello Stephen, 
Is it by design that when a user sorts by owner or assigned to, Ticketdesk sorts by the GUID and not the display name of the user in the Identity users table. 

Regards,
Sai

**Comment by StephenRedd** [comment]
This could be problematic to fix; the user identity stored in the business domain doesn't include the display name information. If we move sorts to the presenter, it would seriously mess with paging and filtering portions of the db queries. Putting the display name info in the business model presents other issues, namely that it has no easy way to keep the business data in sync with changes to the display name that occur in the identity domain.

**Comment by saikovvuri** [comment]
Hey Stephen, 
A similar issue exists with the Ticket status as well. TicketDesk will sort by the enumeration value and not the display text. 

Thanks

**Comment by StephenRedd** [comment]
Digging a bit deeper, this is a much more difficult problem than it initially seems. My first thought was to use lookup tables for the enums, but then what do you do with internationalized versions? The only decent solution that holds up under internationalization would be to push a numeric to name mapping to SQL as part of the query itself (a case statement probably). It will take a bit or work, and it means all the selects for TicketCenter have to be LINQ projections.
