### ISSUE TITLE
Needs localizations

### ISSUE THREAD

**Issue by StephenRedd** [NullDesk/ticketdesk#108]
This issue contains an ongoing list of new resource files, and resource files with new English text. These need to have equivalent translations for the other supported languages (pt-BR, etc.). 

We'll use this issue to collect up the list, and try to get updated translations done near delivery of the full RTM version. 
### New files:
- views/home/accessdenied

**Comment by arleyandrada** [comment]
Pode contar comigo (pt-BR)
You can count on me (en-US)

**Comment by centenario** [comment]
I'm gonna make localization for es-ES

**Comment by arleyandrada** [comment]
Updated localization to pt-BR language.
I suggest to use the ResXManager extension to work with localization.

Localização atualizada para o idioma pt-BR.
Eu sugiro usar a extensão ResXManager para trabalhar com a localização.

https://visualstudiogallery.msdn.microsoft.com/3b64e04c-e8de-4b97-8358-06c73a97cc68

**Comment by feldrim** [comment]
I'd like to contribute, at least for translation but I couldn't hfind a documentation in wiki. It would be good to provide a simple and standardized way for future localizations. I may help in translation in Turkish afterwards.

**Comment by rhan55** [comment]
I'm gonna make localization for tr-TR

**Comment by ganniaiuei** [comment]
I can help with it-IT localization

**Comment by StephenRedd** [comment]
@ganniaiuei Any help is appreciated. For the most part, language localization just involves adding the appropriate resx files. Best bet is to fork the repo, and send a pull request with your localization changes.

**Comment by AlejandroCastrejonItcare** [comment]
If still open I can help with the es-MX  localization working with the clone repo.
