### ISSUE TITLE
EnableEmailNotifications in version 2.5

### ISSUE THREAD

**Issue by easyali** [NullDesk/TicketDesk#110]
Hello,
I have recently downloaded TicketDesk 2.5 and really enjoying it.
I have one pronblem  though. When I create a ticket or when ticket's status changes,
I was expecting to receive email notification. I can see that there is a console application named "TicketDesk.PushNotifications" and this is the one which sends emails. However, my PushNotificationItems and TicketPushNotificationItems tables are empty although 
the following tables have entries in them.

ApplicationPushNotificationSettings
PushNotificationDestinations
SubscriberPushNotificationSettings ---IsEnabled=True

What am I missing?

Thanks,

**Comment by jeffkenn2000** [comment]
Same here.
