### ISSUE TITLE
Who configure notification mail

### ISSUE THREAD

**Issue by vinisdl** [NullDesk/TicketDesk#112]
##Hi I have set up the SMTP port , user , password , however is not sending e-mail when I change a ticket , there is a separate job for sending email?

**Comment by StephenRedd** [comment]
Email is sent by an internal process. Configure it through the UI under push notifications.

**Comment by wbenjamin** [comment]
I am having the same issue.

Push notification info has been set, as well as SMTP settings.

SMTP settings are the same as a different website on the same server that is sending emails.

I'm also seeing no records in the PushNotificationItems table as well as the TicketPushNotificationItems table, though I'm not sure if that is normal or not.

I'm also unsure of when an email should be generated, based on ticket changes..., maybe I'm not setting up the correct scenario to allow the system to send one?

**Comment by StephenRedd** [comment]
Do you have the .Net framework 4.6.2 installed on your server?

**Comment by wbenjamin** [comment]
We do not have 4.6.2 at this time.

Microsoft links for that version are no longer viable from what I have seen, indicating there may be an issue with it?

I did find a link if it is required:

https://www.softexia.com/windows/drivers/microsoft-net-framework-46

**Comment by StephenRedd** [comment]
I wouldn't recommend 4.6.2 yet, I was just wondering --I was running a beta a while back and nothing email related worked until I reverted to 4.6. 

There seems to be something wrong with TD notifications, there are just too many people are reporting similar problems with it. I've not reproduced the issues, but I don't tend to test by using gmail as a relay server (that violates their terms of service anyway). So far, the vast majority of problem reports related to notifications come from people using gmail as a relay though, so it could be something specific about how gmail works. 

Either way, as soon as I wrap up my current project I plan to hit TD notifications with a major round of refactoring; and I'll make sure to do my testing on gmail in addition to the more sane options like sendgrid.
