### ISSUE TITLE
No se me envian los correos

### ISSUE THREAD

**Issue by RamcesCabezas** [NullDesk/TicketDesk#114]
Buenas tardes estimado.

Tengo un problema con el TicketDesk, ya todo el sitema esta montado en mi plataforma, el problema es que las notificaciones no me llegan, ya configure el Push Notification, pero nada no se me mandan
los correos, hay algo mas que hacer previo a la configuración de correo para que este se esta enviando. Mi Configuracion es SMTP.

Saludos.

**Comment by StephenRedd** [comment]
Push notifications do not have broadcast notifications yet. It does not email the person that made the changes, only the other people subscribed. Make sure you are testing with two user accounts. The one making a change will not get a notification. The other should. By default there is a delay in sending messages too. 

<translate>

notificaciones push no tienen notificaciones de transmisión todavía. No se envía por correo electrónico a la persona que hizo los cambios , solamente las otras personas suscritas . Asegúrese de que está probando con dos cuentas de usuario . El que está haciendo un cambio no recibirá una notificación. El otro debería. Por defecto se produce un retraso en el envío de mensajes también.

**Comment by ErickP24** [comment]
Hello, I deployed TicketDesk on IIS server, but i can't receive push notification, when I test on my local machine software sends me notifications.
Could you help me please?
