### ISSUE TITLE
Categories related to Project Settings, not to Aplicattion Settings

### ISSUE THREAD

**Issue by centenario** [NullDesk/TicketDesk#118]
Id like to know if it's possible for future versións that every project can set his own Categories, because every project can be different each other.
Thanks in advance.

**Comment by StephenRedd** [comment]
There are no plans to implement per-project settings or security in TD2. Projects are not intended to be an instancing mechanism, it's just a top level ticket filtering mechanism --a way to group tickets.

My recommendation would be to host two instances of TicketDesk if you have significantly different configurations for different user audiences.

This type of feature will be considered for TD3, along with multi-tenancy. Both are enterprise type features though, and come with some significant administrative complexity that runs contrary to TD's mission to be a super simplified system..
