### ISSUE TITLE
Ticket Owner

### ISSUE THREAD

**Issue by centenario** [NullDesk/TicketDesk#121]
A user with just one role Administrators (only that): i can create ticket, im the owner of the ticket but i can't assign it to myself.
A user with roles Administrator & HelpDeskStaff: i can create ticket, i can assign it to myself but the owner is anothe one (i can select to myself from dropdwon of Owner).
Is it a bug, or is just that funcionality?
For me is better that i can select owner, if im Administrator or even HelpdeskStaff.

**Comment by StephenRedd** [comment]
Is this TD 2.5 or 2.1?

**Comment by centenario** [comment]
Hi,
It's TD 2.5
Thanks

**Comment by StephenRedd** [comment]
Get the latest off develop and see if the current behavior is more in-line with your expectations. 

In the past, TicketDesk has tied available behavior tightly to one specific role, so it required users to have each role for each set of behaviors you wanted them to have. For example, a person in just the admin role would have admin abilities, but not be able to create tickets, nor be assigned tickets; if you wanted an admin to do those things you'd need to give them all three roles. 

For TD 2.5, the intent has been to have the roles be incrementally more permissive, users would have create ticket behaviors, staff would have those plus ticket assignment behaviors, and admins would have all permissions from both lesser roles plus the admin specific behaviors.

This has now been implemented with #122
