### ISSUE TITLE
table PushNotificationItems are not getting any data

### ISSUE THREAD

**Issue by odtoro** [NullDesk/TicketDesk#128]
I already configured the notification integration but i'm not getting any data filled in the notifications tables, what i am missing?
thanks in advance.

**Comment by StephenRedd** [comment]
I'm working on a complete overhaul to the entire mail system top-to-bottom. Sorry for the delay

**Comment by StephenRedd** [comment]
The main problem with the existing system has been repaired and pushed to the develop branch. Sorry for the delay in getting this addressed.
