### ISSUE TITLE
Create database not working

### ISSUE THREAD

**Issue by jeffkenn2000** [NullDesk/TicketDesk#130]
After the application comes up and I put in my credential to create a new admin account, it gets an error that it cannot access the database. I did notice that I do not have the .mdf file in my code download.

Has anyone else had this issue? 

Thanks

**Comment by StephenRedd** [comment]
Which version are you running?

**Comment by jeffkenn2000** [comment]
2.5 but it was my fault. The  sql  server I was trying to connect to was 2014 and i had the credentials wrong. 

Amazing work by the way. 

Thanks,

**Comment by StephenRedd** [comment]
Ah, no worries then. Thanks :)
