### ISSUE TITLE
Clicking TicketCenter by HelpDesk user gives NullReferenceException

### ISSUE THREAD

**Issue by PrasannaMishra1** [NullDesk/TicketDesk#132]
Version: 2.5 Beta (tag td2-v2.5.0)
Download: TicketDesk.2.5.0-beta.Compiled.zip from https://github.com/NullDesk/TicketDesk/releases/tag/td2-v2.5.0

Issue Description: 
When logged on to the system as HelpDesk User, on clicking TicketCenter the site errors out. Attached the error shown on a browser. When Logged in as Internal User or Admin the issue is not seen.

Steps to Reproduce:

1. Using Internal User create a ticket
2. Click on TicketCenter, a list of Tickets will be shown
3. Logout 
4. Login as HelpDesk user
5. Click on the TicketCenter link on the top menu
6. Browser shows error. Object reference not set to an instance of an object.

[TicketDeskError.html.txt](https://github.com/NullDesk/TicketDesk/files/774436/TicketDeskError.html.txt)

**Comment by StephenRedd** [comment]
This appears to have been related to problems with multi-project support. Should be fixed in release td2-v2.5.1
