### ISSUE TITLE
Not able to use need help in configuration

### ISSUE THREAD

**Issue by Anitak12345** [NullDesk/TicketDesk#135]
Hi,

i am trying to run this. but it is stuck on first page only. even if you login it is on same screen.
please help me to deploy this application.
thanks.

**Comment by StephenRedd** [comment]
I think I need more information about what the behavior you are seeing looks like. If you deployed the stock application, your first screen should be the first-run-setup for creating the database. Is that what you are getting, and if so what happens when you try to create the database?
