### ISSUE TITLE
How do I see the Assign button on Unassigned tickets?

### ISSUE THREAD

**Issue by MarkHackenberg** [NullDesk/TicketDesk#136]
Hi,

I am using TicketDesk 2.1 and we're using single sign on.

I cannot see the Assign button on any Unassigned tickets.  I am part of the admin group we created for TicketDesk in our Active Directory.  Is there anything I can do to the Assign button on Unassigned tickets?  it is not there on tickets created by me or anyone else.

Thanks,

Mark
![assign button missing issue](https://cloud.githubusercontent.com/assets/28306567/25641220/08d66042-2f61-11e7-9e3b-95c476a692c2.png)

**Comment by StephenRedd** [comment]
You by default, you should be be logged in with an account that is a member of the help desk staff role to assign tickets.  

There is a setting in application settings to allow regular users to assign the tickets when they are created, but this setting only applies to the new ticket form. They cannot assign or re-assign tickets that already exist.

**Comment by MarkHackenberg** [comment]
Thanks!  I just had to add my domain user to the help desk AD group I created.  When I did that, the Assign and Take Over button appeared.
