### ISSUE TITLE
Error after login as "demo" admin

### ISSUE THREAD

**Issue by SaschaLorenzHH** [NullDesk/TicketDesk#137]
Cool project! But i have an error after login as "default" admin (TicketDesk 2.5 (beta) )

my own user works fine. 

![image](https://cloud.githubusercontent.com/assets/29090883/26624320/d37985f4-45f0-11e7-96cb-0115fc2a70e2.png)

**Comment by StephenRedd** [comment]
I can't see any simple way to reproduce this problem. Can you check to make sure your web.config includes an appsettings key such as:

```
    <add key="ticketdesk:DemoModeEnabled" value="false" />

```

**Comment by AGitDev** [comment]
I experienced the same problem, and found that the following small change removed the error:
After **line 122** of **ticket.desk.web.client/controllers/UserController.cs**
(i.e. within `public async Task<ActionResult> SignIn(UserSignInViewModel model, string returnUrl)`)
add:
`ViewBag.IsDemoMode = (ConfigurationManager.AppSettings["ticketdesk:DemoModeEnabled"] ?? "false").Equals("true", StringComparison.InvariantCultureIgnoreCase);`

Hope this helps.

**Comment by StephenRedd** [comment]
Thanks for tracking this down!
