### ISSUE TITLE
Project and todo task list

### ISSUE THREAD

**Issue by vinisdl** [NullDesk/TicketDesk#138]
[EN]
It would be nice to create a project and create the tasks that are waiting, in progress, and finished to track and maybe even execute them.
[PT-BR]
Seria legal criar um projeto e criar as tarefas que estão aguardando, em progresso, e finalizada para acompanharmos e talvez até executarmos elas.

![image](https://cloud.githubusercontent.com/assets/6885761/26633624/67f64520-45ea-11e7-8708-cc933a38a31b.png)

**Comment by StephenRedd** [comment]
I typically use [ZenHub](https://www.zenhub.com/) for project management on GitHub. It's a free add-on for everyone when working with open source projects. 

TicketDesk has a ZenHub board setup, and past milestones used ZenHub well... but the project is way behind schedule at this point. The board is nearly useless. 

I'm currently putting together a new plan for TicketDesk, and when I am ready to move forward again I'll likely move the new development to a new repo. I'll look into setting up a traditional GitHub project for that.
