### ISSUE TITLE
Having a summernote problem

### ISSUE THREAD

**Issue by spindlegoose** [NullDesk/TicketDesk#143]
In IE and chrome and I get an error displaying in the console 

SCRIPT5007: Unable to get property 'jQuery222077527682391688552' of undefined or null reference
jquery-2.2.2.js (3747,3)

I have upgraded bootstrap (3.3.7), jquery(3.1.1), and summernote (0.8.7) and still get the error.

SCRIPT5007: Unable to get property 'jQuery3110104176465542514362' of undefined or null reference
jquery-3.1.1.js (4085,3)

 Is this happening for you guys or do I have something potentially setup wrong?

**Comment by StephenRedd** [comment]
Looks like an issue with validation. Update the nuget package for JQuery.Validation to 1.16.0, and the problem should go away.

**Comment by spindlegoose** [comment]
Thank you for the update. After I updated jquery.validation I was receiving other errors. It appears summernote and validation don't play well together so I added the line below after the summernote initialization and all works well now.

 jQuery.validator.setDefaults({
                    // This will ignore all hidden elements alongside `contenteditable` elements
                    // that have no `name` attribute
                   ignore: ":hidden:not(#wmd-input-ticketDetails), [contenteditable='true']:not([name])"
                });

**Comment by StephenRedd** [comment]
I wasn't seeing the other errors after updating JQuery.Validation, but it could be due to other upgrades (bootstrap, jquery itself, etc.).

Honestly, not much plays nice with JQuery.Validation these days... it's an older UI stack, and over the years support for older components has been spotty.
