### ISSUE TITLE
Convert TicketDesk to Asp.Net Core (2.x)

### ISSUE THREAD

**Issue by a-patel** [NullDesk/TicketDesk#146]

**Comment by StephenRedd** [comment]
Ticketdesk 3 will be built on asp.net core, but it will not be a conversion of the existing code. It will be a re-write using all new technologies.

**Comment by a-patel** [comment]
that's great, thanks @StephenRedd

**Comment by a-patel** [comment]
@StephenRedd 
any update?
like new branch or new project?

**Comment by StephenRedd** [comment]
I do have an experimental private repo setup for TD 3, and I've been working little by little on it over the last couple of months,  but it isn't ready to share with the community. It is in the late prototype stages, while I work out an overall architecture and nail down a final tech-stack. 

I'm also revisiting the features and requirements. There will be some fundamental differences from TD 1 and 2. 

While nothing is finalized, here is what I will say based the prototype so far:

- This is a new code implementation end-to-end
- Server is cross-platform ASP.NET Core
- The general architecture is DDD + CQRS + ES
- It offers more than one data store option
  - The initial development focuses on MongoDB/CosmosDB
- The front-end targets Angular @latest

**Comment by a-patel** [comment]
@StephenRedd 
Thanks for your reply and re-opening the issue.

I can help you in TD ASP.NET Core development, if you want.

**Comment by a-patel** [comment]
Any roadmap?

**Comment by vinisdl** [comment]
Open for contribute.

**Comment by picflight** [comment]
Hello StephenRedd,

Are there any updates available on the next updates?

Thx
