### ISSUE TITLE
office 365 oAuth

### ISSUE THREAD

**Issue by mikelowen93** [NullDesk/TicketDesk#149]
Hello im trying to enable microsoft authenticacion in TicketDesk app and i can't log in with microsoft auth, is there a litle tutorial how to enable it?

a lot of thanks

**Comment by StephenRedd** [comment]
This came up in another conversation recently. The short answer is that TD wasn't designed with oAuth support out of the box, but you can add external authentication to it with some refactoring.

The longer answer:

The original startup auth file came from the boilerplate template (the standard asp.net project template that shipped with whatever version of visual studio I used back then). 

TicketDesk’s authentication follows the same overall design as the stock template; aspnet.identity with an application sign-in manager class, and some local controllers and views to handle the actual UI. But in TicketDesk’s case, these were customized a good bit too; I’ve never actually intended to support external logins in TD 2.5 though, so I removed most of the original code that dealt with external authentication scenarios, especially in the controller and user manager. 

I’m pretty sure you could still enable external login providers, and modify ticketdesk to work with them. It wouldn’t be too much trouble I imagine, but it will require some recoding and refactoring. 

Still, even in VS 2017 you can go to file -> new project, choose the ASP.NET template (from .net 4.6.2), pick MVC from the template dialog then click the “change authentication” button and set it to “individual user accounts”. This will generates pretty much the same project I started with, with the same auth mechanisms as the one ticketdesk was based on. The current stock templates are a little simpler than the old ones, and the UI is more comprehensive, but overall it has the same parts –and ticketdesk has those same parts too, just move around to other places. 

You could probably compare a stock new project, and then borrow the original templates code to re-integrate that functionality into ticketdesk.
