### ISSUE TITLE
Is there max upload size for attachments

### ISSUE THREAD

**Issue by MarkHackenberg** [NullDesk/TicketDesk#156]
Hi,

Just a quick questions.  Is there a max filesize that is allowed to be uploaded as an attachment?  Is this value controlled anywhere is the database or config file if so?

Thanks,

Mark

**Comment by StephenRedd** [comment]
It depends on where you are hosting the application, and what the settings are for that environment -- but yea, just like any asp.net application there are limits in both request length and time; all can usually be configured via web.config:

https://forums.asp.net/post/5451137.aspx
