### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by jeffkenn2000** [NullDesk/TicketDesk#157]
Has there been any progress on getting email notifications to work?

**Comment by jeffkenn2000** [comment]
Has anyone come up with a solution for ticket notification

**Comment by jeffkenn2000** [comment]
Can you use the notification job without using azure? I'm hosting the application locally.

**Comment by StephenRedd** [comment]
If you aren't using azure, TD will automatically use an in-process delivery system instead -- so mail would be delivered from a timer job running in the site.

**Comment by jeffkenn2000** [comment]
Do I need to do anything special if I have it hosted in iis?

It’s odd, sometimes the nicely formatted emails just send to people but
when I update a ticket it doesn’t always happen.
