### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by afabri73** [NullDesk/TicketDesk#159]
Hi,
I download and installed the last source code of ticketdesk.
With some changes it finally function properly...but...I have a problem with localization.
I tried to add the italian localization and when I click on italian language in navbar, nothing appears.
The language is always english.

I explain what I've done.
First of all in the TicketDesk.Localization project I created all italian resource file
I also changed this code in CultureHelper.cs
```
        // Include ONLY cultures you are implementing
        private static readonly Dictionary<string, string> _cultures = new Dictionary<string, string> {
            {"en-US", "English"}, // United States English culture
            {"it-IT", "Italiano" }, // Italian culture
            {"pt-BR", "Português do Brasil"}  // Brazilian Portuguese culture
        };
```
What else can I do to make the localizzation work?
Thank you
Adriano

P.S. Sorry my not perfect english :-)

**Comment by StephenRedd** [comment]
Please refer to the recent commit by soaTf. It adds localization successfully. The build action for the resource files should be set to Embedded Resource. Otherwise, the change you show above should be all you need.

https://github.com/NullDesk/ticketdesk/commit/110dfedb3a819ea056d466181575a7fc55f9b9a9

**Comment by Mox72** [comment]
I translated and added the Italian language (see attached project).

[TicketDesk.Localization.zip](https://github.com/NullDesk/ticketdesk/files/1771267/TicketDesk.Localization.zip)

**Comment by StephenRedd** [comment]
I'll see about merging this and getting a PR in place for it

**Comment by Mox72** [comment]
Sorry Stephen, i worked on a old version, soon i will work on the latest version of TicketDesk and I will send you the new project
