### ISSUE TITLE
Active Directory Log in and Extternal login

### ISSUE THREAD

**Issue by MarkHackenberg** [NullDesk/TicketDesk#160]
Hi,

if we are using the AD login right now (SSO), is there a way to still login outside of the network?

We have a building that has a VPN to our network (so they are access the URL ticketdesk is on), but they are not on our domain.  TD works fine if you're in the building using SSO.

Is there a way I could set up users at that location to use username/password / email while we use SSO in our building?

Thanks,

Mark

**Comment by StephenRedd** [comment]
Not without re-coding the authentication a good bit. Hybrid authentication is a complete bear to implement; and I wouldn't even recommend you try it with a modern system. Instead, consider using a federated authentication mechanism (OpenID Connect for example) and connect it to your AD via ADFS (or through Azure AD). This can be a very complex topic though, and a lot depends on your server tech and network topology.
