### ISSUE TITLE
Initial setting

### ISSUE THREAD

**Issue by milovidov983** [NullDesk/TicketDesk#162]
I started the application TicketDesk 2.5 (beta), but I do not know how to log in to the admin panel, it asks for e-mail.... You wrote that there will be a stage of creating a database but this did not happen, I immediately saw the main application window....
![default](https://user-images.githubusercontent.com/5534561/36715428-390f2086-1ba7-11e8-806d-55dbadb83b7a.JPG)

**Comment by StephenRedd** [comment]
I am not sure how that could happen -- source control shouldn't contain a database at all, so it'd have to go to the setup page first to create one (http://whatever/first-run-setup).

I do think there may be an issue with logging in with the current head of the develop branch though -- we merged in some changes recently. I was planning to look into that a bit more to be sure. You might want to stick to the master branch if you have issues.

**Comment by StephenRedd** [comment]
Actually, you can disregard the issue with logins on develop branch -- turns out that was a local issue with my own browser. Seems to work correctly.
