### ISSUE TITLE
Export ticket data

### ISSUE THREAD

**Issue by ultramanbank** [NullDesk/TicketDesk#166]
I need export ticket data to excel file

**Comment by StephenRedd** [comment]
That's fairly straight forward to do usually. TicketDesk's database schema isn't very complex; you can use SSMS to write a query that produces the data you want and export it to csv. You can also link Excel directly to the SQL server and do some quite advanced stuff with the data too.

**Comment by ultramanbank** [comment]
This feature i request for user isn't know how to write a query or connect to database.

**Comment by StephenRedd** [comment]
It would be trivial to add an admin feature for exporting all ticket data in a hierarchical format -- json or xml. 

For flattened output like excel, exporting the top-level ticket record is no problem. 

But if you want the activity history, flattening the structure gets odd. There are a lot of strategies for flattening heirarchies, and each has advantages and disadvantages. The two main ones are:

- You can flatten the data, one row per activity item, and just duplicate the parent data in each row. 
- You can use a column to denote record type, and populate different columns depending if the row is from the parent table or the child table. 

It also helps to understand why you'd want a flattened export -- what is the intended purpose of the export? If it's just for downloading a copy of raw data then xml or json would be much better options.

If there is some reason it needs to be excel, it would help to know why. 

Also, is the export request specifically for excel, or just something that works with excel (like std CSV)? 

And of course, what is the desired format of the output (if flattened to csv or excel)?
