### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by StephenRedd** [NullDesk/ticketdesk#17]
Replace home page with user-specific dashboard instead. This will be simplistic in the first cut.

**Comment by saikovvuri** [comment]
Hello Stephen,  will the dashboard feature be available in your 8/1 publish. 

Thanks

**Comment by StephenRedd** [comment]
It is scheduled for the 2.5 milestone, which is expected on or about August 1st.

**Comment by saikovvuri** [comment]
Hello Stephen - hope you are doing well,  just checking when are you planning to release the 2.5 milestone. 

Thank you.

**Comment by StephenRedd** [comment]
I've had some priority shifts at my paying job over the last few weeks, but I plan to get back to TD 2.5 next week. It will be about three more weeks before I can get it to the final 2.5 milestone though.

**Comment by feldrim** [comment]
A [Freeboard](https://github.com/Freeboard/freeboard) implementation would be useful, I believe.
