### ISSUE TITLE
Network problem

### ISSUE THREAD

**Issue by iglillambiri** [NullDesk/TicketDesk#171]
Is it possible to access this software via the network, if yes, please let me know how to do so?

**Comment by mPisano** [comment]
Yes, It's a browser based application? 
locally, Instead of localhost or 127.0.0.1 you would use the ip address of the machine running IIS,
If you mean publicly, you would register a DNS name against the static address from your ISP and port forward on your firewall or host it in Azure.
HTH - Mike
