### ISSUE TITLE
Service Level Agreement (SLA)

### ISSUE THREAD

**Issue by gasquare** [NullDesk/TicketDesk#178]
Is it possible to add a SLA(s) for the ticket . If yes is there any tips on how to achieve it.

**Comment by StephenRedd** [comment]
You could attach an SLA to the ticket as a document, or you could just give each of your SLA a name and use tags to indicate which apply to the ticket. There is nothing out-of-box related to SLAs directly... contract management and legal document/content management are a bit beyond the initial scope the project had in mind.
