### ISSUE TITLE
Roadmap: TicketDesk version 3.x (in ASP.NET Core 3.x)

### ISSUE THREAD

**Issue by a-patel** [NullDesk/TicketDesk#180]
Any roadmap decided for version 3.0?

**Comment by a-patel** [comment]
@StephenRedd any update on a new version?

**Comment by StephenRedd** [comment]
No actually. I have ideas of course, and I've done several prototypes of a next version over the years -- but haven't had enough time to fully commit to undertaking the project. At this point though, if I were to do a new version myself it would be completely new -- like a new repository, new tech stack, new everything kind of new. 

Any particular suggestions or ideas on what you'd like to see in a v3?

**Comment by a-patel** [comment]
Hi @StephenRedd ,
Thanks for reverting at earliest.
As a developer, I am looking for a new Technology stack.

- .NET Core 3.0
- ASP.NET Core 3.0
- Entity Framework Core 3.0
- C# 8
- ASP.NET Core MVC - View Engine preferable (instead SPA in Angular) - my personal  suggestion
- Pluggable/Modular Architecture 
- Repository Pattern (Generic)

Many other things related to project architecture.

Use third party libraries - Don't reinvent the Wheel

- DI-IoC - Autofac
- Object Mapping - AutoMapper
- Validation - FluentValidation
- Background Job - Hangfire
- Event Sourcing (CQRS) - MediatR
- Logging - Serilog
- OpenIdDict - WebAPI Authentication

And many more libraries are there.

**I am very happy to contribute to the new Version.**

**Comment by StephenRedd** [comment]
I have thought about this a good bit recently, and I think I will put together a prototype stack for it as soon as .NET Core 3x goes to RTM . 

For me, the primary incentive has always been learning new things, and in this case I'm leaning towards using Blazor for the UI. 

I'm also debating moving it away from EF Core -- these days I tend to architect in a way that isolates infrastructure dependencies; so different back-end stores are fairly simple to support, but I think the initial store we start with may not be a relational store; especially if event sourcing the direction we go.

**Comment by a-patel** [comment]
@StephenRedd Any update on this?

**Comment by a-patel** [comment]
.NET Core 3.1 LTS is out. Any update on this?
@StephenRedd

**Comment by a-patel** [comment]
Any update, @StephenRedd ?

**Comment by a-patel** [comment]
Any update, @StephenRedd ?

**Comment by a-patel** [comment]
@StephenRedd any update on this?
