### ISSUE TITLE
Due By

### ISSUE THREAD

**Issue by BrendanThompson** [NullDesk/ticketdesk#25]
Have the option to set a Due Date for a ticket

**Comment by saikovvuri** [comment]
Hello Stephen - will the Due Date functionality be available in the 8/1/2015 release

**Comment by StephenRedd** [comment]
It is scheduled for the 2.5 milestone, which is expected on or about August 1st.

**Comment by saikovvuri** [comment]
Hi Stephen, 
Is the [due by] feature being implemented the way you suggested meaning start date and due date field along with some scheduling and time management features?

Thanks.

**Comment by StephenRedd** [comment]
This issue only addresses the due date field, and visual indicators for over-due tickets. So far, this is the only feature we've committed to deliver in the TD 2.5 time-frame. 

The business case here is to let users indicate (optionally) which tickets might have some time-sensitive aspect or critical deadline; and then provide cues to show when an issue approaches or exceeds that deadlines --the goal is to just to help users prioritize their work.

As I noted above, I have reservations about adding a start date field. From discussions on #84, it also seems that a optional, user-editable start date field would not be very useful to your business case.  

> You likely need customized notion of start date, and customized screen output or reporting. I'll gladly help you out with that. Fork the code and reference me on an issue, or just email me out-of-band and we can discuss your particular requirements in more detail (email is in my profile).

The general problem with a start date field is that there are several business domains that have different requirements for that field. Before we introduce a formal start date, we need to very clear about what specific business requirement we intend to address.  

The business domains where start date is useful are scheduling, billing, and individual time accounting -- project management, operations, and business management. All of these have some notion of start date, but the meaning of that field, and the behaviors attached to it, differ drastically in each.

Support for client billing scenarios on a per-ticket or per-project basis is planned (tentatively) for implementation in TD 2.7. Before it can be implemented though, we need a more flexible and configurable security system (TD 2.6), then we need external user related features (TD 2.7). 

Scheduling is a possibility, but probably not in the short-term. The features around scheduling really need the extra UI glitz of a *js framework; which we'll have eventually in TD 3.  

User specific time accounting is frequently requested, either for payroll type uses (time-sheets), or for user performance measurement. Payroll type time keeping is too far outside TD's core mission, and user performance measurement leads to measurement dysfunction.

If people want to use the data TicketDesk tracks for the purpose of individual user time reporting, then I'm fine with it. I'll even help people code their own custom time reporting solutions where I can, especially if it's on a forked repo others might be interested in. I do recognize that there are (a few) legitimate business cases where individual time reporting becomes a necessary evil.

But I won't encourage measurement dysfunction by including features in the core TicketDesk product that measure individual performance.

**Comment by wpywong** [comment]
Hi Stephen,

I have forked the repository and build the solution from the develop branch and could not find the due date field? BTW, I found that the HTML editor is not working as expected. May I ask am I doing something stupidly wrong?

Thanks.

**Comment by StephenRedd** [comment]
No, you aren't doing anything wrong. This issue is old, but still open. Feel free to read through the discussion, implement this in a way you find most appropriate, and send over a pull request.  

As you can probably tell from the dates and commit history, I have not made a lot of changes to this repo in a while. I do have plans for future work on a new version at some point, but I have no plans to make significant investments for v2.5. Instead, future development would happen in a new 3.0 specific repository, and would implement a fresh take on ticketdesk using more modern UI and .NET core technologies.   

However; I will happily take pull requests for v2.5 from the community, and will assist where I can.
