### ISSUE TITLE
Dropzone update breaks layout

### ISSUE THREAD

**Issue by StephenRedd** [NullDesk/TicketDesk#44]
The new version of dropzone includes major improvements to the previews, but come with breaking changes. Need to update TicketDesk for the new version's changes.

**Comment by lpawlak** [comment]
Hi,
I confirm - latest version breaks layout.
![dropzone](https://cloud.githubusercontent.com/assets/8555321/7294990/677af2a8-e9b2-11e4-9a3f-20f75085b8d8.PNG)
Which version of dropzone have correct layout?

**Comment by StephenRedd** [comment]
Dropzone 3.10.2 worked, dropzone 4.0.x changed their preview layout and styles. Shouldn't be difficult to update ticketdesk to use the new dz preview layout.

**Comment by Wootz** [comment]
I have fixed this issue. please refer  as below code.

css url is wrong
TicketDesk-2.5/TicketDesk.Web.Client/App_Start/Startup.Bundles.cs
Line 39:`	.Include("~/Scripts/dropzone`~~/css~~`/dropzone.css", new CssRewriteUrlTransform())`
Line 40:`	.Include("~/Scripts/dropzone`~~/css~~`/basic.css", new CssRewriteUrlTransform()));`

TicketDesk-2.5/TicketDesk.Web.Client/Views/Ticket/New.cshtml    (Line 158 ~ 163)
TicketDesk-2.5/TicketDesk.Web.Client/Views/TicketActivity/_ModifyAttachments.cshtml    (Line 20 ~25)
`<div class="col-md-8 col-sm-11">`
　`<div class="dropzone" style="min-height: 40px;" id="attachmentsDropZone">`
　　`<span class="dz-message" data-dz-message><i class="fa fa-download fa-3x"></i> Drop attachments here, or click to select files.</span>`
　`</div>`
　`<div class="dropzone-previews" id="dz-preview"></div>`
`</div>`

The element `<div class="dropzone-previews" id="dz-preview"></div>` should be in `<div class="dropzone" style="min-height: 40px;" id="attachmentsDropZone">` element.

**Comment by StephenRedd** [comment]
Thanks for taking care of that Wootz, the changes are now committed.
