### ISSUE TITLE
No tickets? "Object reference not set to an instance of an object." Error..

### ISSUE THREAD

**Issue by Ryanb58** [NullDesk/TicketDesk#47]
I went to the http://ticketdesk2.azurewebsites.net/ website to try out the new alpha version of ticket desk. Logged in as admin, then under the manage demo data page, I removed the data. Tried navigating to the 'ticket center' page, and got an "Object reference not set to an instance of an object." Error.. seems like you guys might not be checking to ensure the list has items in it before pushing to observable collection to the view(assumption).

**Comment by StephenRedd** [comment]
The version that was on demo had some issues regenerating the users when you removed the demo data. Unless you were quick to regenerate the demo data immediately after removing the data (without logging out), you would not be able to do much of anything. 

I pushed a new version up today that shouldn't have that problem. Unfortunately, continuous integration is busted right now thanks to a problem in kudu (see #1485)
