### ISSUE TITLE
Register action throw an exception in develop branch.

### ISSUE THREAD

**Issue by Wootz** [NullDesk/TicketDesk#54]
The TicketDesk-2.5 throw an exception when i register a new user.

TicketDesk/TicketDesk-2.5/TicketDesk.Web.Client/Controllers/AccountController.cs
Line 188: `var filterColumns = CurrentListSetting.FilterColumns.ToList();`

Error Message:
The ObjectContext instance has been disposed and can no longer be used for operations that require a connection.

**Comment by StephenRedd** [comment]
We have to rebuild the user management stuff anyway, so this will be addressed along with issue #6.
