### ISSUE TITLE
Error in TicketCenter, when regular user access that.(develop branch)

### ISSUE THREAD

**Issue by Wootz** [NullDesk/TicketDesk#55]
When regular user access ticket center index page, there is throw an exception that is System.NullReferenceException.

Because the default listName has been set up for "myTickets" by Index action in TicketCenterController , 
>TicketDesk/TicketDesk-2.5/TicketDesk.Web.Client/Controllers/TicketCenterController.cs
Line: 49
`listName = listName ?? (Context.SecurityProvider.IsTdHelpDeskUser ? "unassigned" : `**`"myTickets"`**`);`

But the listName is "mytickets" in the DefaultListSettings.
>TicketDesk/TicketDesk-2.5/TicketDesk.Domain/Model/UserSettingsModel/UserTicketListModel/
Line:185
`settings.Add(new UserTicketListSetting(`**`"mytickets"`**`, TicketDeskDomainText.DefaultListNameMyTickets, disOrder++, 20, mySortColumns, myFilterColumns, disableOwnerColumn));`

So, I change this code at UserSetting.cs in my project.
>TicketDesk/TicketDesk-2.5/TicketDesk.Domain/Model/UserSetting.cs
Line: 3
`return ListSettings.FirstOrDefault(us => `~~`us.ListName == listName`~~` `**`string.Compare(us.ListName, listName, true) == 0`**`);`

The above is provided for your reference.

**Comment by StephenRedd** [comment]
Thanks again Wootz! I'll get that fixed up asap. I've been moving a lot of code in the last couple of weeks, but I need to do a better job with regression testing.
