### ISSUE TITLE
Authorization - forgot password and account confirmation

### ISSUE THREAD

**Issue by StephenRedd** [NullDesk/ticketdesk#59]
implement reset and recover password features, and account confirmation on login:

[Check this for a detailed overview of standard implementations](http://www.asp.net/identity/overview/features-api/account-confirmation-and-password-recovery-with-aspnet-identity)

Security settings should control if this is enabled. If no email delivery provider, override/disable. Use the standard generated reset token and email user flow.

**Comment by jeffkenn2000** [comment]
Was this ever implemented? 

I cannot find it in the current code base.

Thanks,

**Comment by ransems** [comment]
This is quite important in any application. Anyone working on this? Makes the system nearly unusable if we do not have it.

**Comment by jeffkenn2000** [comment]
Im trying to create something now.
