### ISSUE TITLE
Manage Users has no way to actually add a user

### ISSUE THREAD

**Issue by gavsto** [NullDesk/ticketdesk#85]
Hi Stephen,

Hope you're well. I see the upcoming version of TicketDesk is shaping up very nicely! I'm taking a run through it at the moment and I can't see anywhere to actually add a new user in user management. I assume that is by design and you are probably populating this from users who have registered initially but do you think it would be worthwhile to give Administrators the ability to actually generate a user?

**Comment by StephenRedd** [comment]
We'll take a look at adding this to the user admin pages in the 2.6 milestone (which overhauls the security system and adds organizational security options). Of course, there is nothing to stop the admin from just using the current registration page to create new user accounts.
