### ISSUE TITLE
SSL - certificate problem 

### ISSUE THREAD

**Issue by krtezech** [NullDesk/TicketDesk#90]
Hello,

Iam gettin' an issue with ssl certificate in visual studio 2012, using Internet Explorer11

"There is a problem with this website's security certificate"

Should I install manually some certificate, or what can I do please (: .

Thank You.

**Comment by StephenRedd** [comment]
This is a common problem with self-signed SSL certificates. Using self-signed SSL Certificates requires you to manually configure IE to trust the certificate. [See here for full instructions](http://blogs.msdn.com/b/robert_mcmurray/archive/2013/11/15/how-to-trust-the-iis-express-self-signed-certificate.aspx)

If you upgrade to VS 2013 or 2015, then Visual Studio should automatically take care of setting up trust for SSL certificates.

**Comment by krtezech** [comment]
Thanks for quick reply,

The question was rather about that, if every user will have to manually install and confirm that.

OK, I'ill try a never VS. Thank You.

**Comment by StephenRedd** [comment]
For production, you'd want to install a real SSL cert from one of the trusted vendors on your web server, in which case users won't see any problems with the cert's authenticity.

**Comment by krtezech** [comment]
oh you're right! Thanks.
