### ISSUE TITLE
New ticket creation problem

### ISSUE THREAD

**Issue by krtezech** [NullDesk/TicketDesk#93]
Hallo !

Well it's a bit complicated, so I hope you'ill understand. I Am sorry for my bad English.
What happened:

1) I configured the SMTP in the admin section. Iam using postfix email.
2) I tried to change Admin user profile, to set my local email instead of that "admin@example.com". it seemed like it works, but after few minutes when I get the error on new ticket creation action, I figured out that it's back again on "admin@example.com".
3) so I registered new user, with finally my local smtp email address
4) assigned the role "Help Desk Staff" for my new user
5) new ticket creation now causes an error:

"Sequence contains no elements" 

Line 177:                //set to first project if only one project exists, otherwise use user's selected project
Line 178:                ticket.ProjectId = (isMulti) ? await Context.UserSettingsManager.GetUserSelectedProjectIdAsync(Context) : projects.First().ProjectId; 

Thank You, Paul.

**Comment by krtezech** [comment]
Oh I figured out what caused that - the "Default" project has disappeared. I mean literally. And I don't see any option for deleting projects, so user actually cannot delete the projects.

Thank you for your attention.

**Comment by StephenRedd** [comment]
Projects can be deleted, just not the last (only) project. I can't see any way to reproduce the removal of a project by accident, nor is there a likely place where a bug might cause this side-effect. The only place this might come up is if you have demo mode enabled, or manually blow-away and/or recreate data using the demo data manager UI.

Please reopen if seen again.

**Comment by Oxymoron290** [comment]
is this ticket still open?

**Comment by StephenRedd** [comment]
it's on the board as done but not closed, but I've left it until we have had more time to verify the resolution.
