### ISSUE TITLE
New features suggestion

### ISSUE THREAD

**Issue by krtezech** [NullDesk/TicketDesk#96]
Hello!
I would like to suggest some more ideas, that could be new features for this ticketing system. I apologize for my sometimes poor English.

- splitting of tickets
I think there should be a feature, that you can split some tickets into several sub-tickets. These should be linked with the main ticket and for example the main ticket should not be closed until all of the sub-tickets are solved out.

- merge tickets
Merging of tickets - make from 2 familiar ticket requests just the one, or remove duplicities.

- SLA
SLA is an important feature when you need to solve the tickets in some time limit. For example "guarantee a maximum time limit of solving problems". You should be able to set these time limits for tickets with priorities. When the time limit is expired or near the expiration of SLA limit, it should get a higher priority or something that allerts an agent of TicketDesk. There should be also some report, of TicketDesk agents, how are they good within time limits of SLA.

- L1 & L2 & L3 support
For example it's good to have a queues and subqueues for tickets. All new tickets should be assigned by L1 to L2 support. L2 support should tell if they are able to solve the problem, when they are not, it should be passed to L3 developers. While L1, L2 and L3 should not know the exact person, of L1, L2 or L3 support, they should pick their tickets from a queue or somewhere. I hope you get the idea.

I have even some more ideas, so tell me please if it's welcome.
Have a nice day and thank You.

**Comment by StephenRedd** [comment]
Ideas are always welcome. 

Mechanisms to deal with duplicate tickets, splitting tickets, and soft-linking between related tickets are all under consideration, and will likely appear in the near future. 

Sub-tickets will probably not be implemented, at least not in the traditional way. The use cases that demand hierarchical relationships between tickets are usually features around project management. While it often seems that support issue and project issue tracking are similar, there are quite a number of significant behavioral differences. A system modeled to be a good project tracker becomes too clunky and hard to use for traditional support issue  tracking, while a good support tracker is too limited to make a good project management tool. There are plans around implementing sub-tasks (task checklists) within tickets, but these will likely take a simpler approach than a ticket hierarchy.

Features that involve SLA's and tiered support levels are already planned for implementation in near-future versions (starting with TicketDesk 2.7). TicketDesk's focus until now has been internal use within a single organization. TD 2.7 is intended to open up scenarios for shops providing support services to external users, or contract services for other organizations.
