### ISSUE TITLE
Null reference exception when attempting to list tickets

### ISSUE THREAD

**Issue by IanYates** [NullDesk/TicketDesk#99]
I've been playing with TicketDesk internally - looks great! :)

On my 3rd user I created a non-administrator.  He then logged in to the system.  I then gave him extra roles.
He can't view tickets - we get a null reference exception in the `TicketCenterListViewModel.ListTicketsAsync` call, specifically `CurrentListSetting` being null.

It's null because that user's ListSettingsJson field in the database is populated (so no defaults are recalculated) but there's no value in there for the "unsigned" list.

I've dug around the code and could see a few places where it might be appropriate to slip in a check to see if a request is being made for a user list configuration that should exist but doesn't.  I wasn't sure of the best place as I've only spent about 10 minutes getting familiar with the code.  At the moment I've just patched `TicketCenterListViewModel.GetViewModelAsync`, adding in 
```
if (vm.CurrentListSetting == null)
            {
                //fall back to default list setting
                vm.CurrentListSetting =
                    UserSetting.GetDefaultSettingsForUser(userId,
                        context.SecurityProvider.IsTdHelpDeskUser || context.SecurityProvider.IsTdAdministrator)
                        .GetUserListSettingByName(listName);
            }
```
after the creation of the vm variable.  This feels like a dirty hack.  Any suggestions on how to better cope with this.  The code that fills in the defaults for the user only does so if the user has NO settings at all.  This user has settings, it's just that he needs more settings (which we could sensibly populate from the defaults). 

After that patch I'm now getting a different error to do with 
The query syntax is not valid. Near term '@AssignedTo', line 8, column 66. 
when trying to retrieve a list of items - I'll dig into that one separately...

**Comment by vanquocktcn** [comment]
hey you, i want it, never igion it. i very like it. 2000$ ok

-----Original Message-----
